Replace from_creation_date in favor of a cross platform solution
Proryanator/encoder-benchmark pull request #23
Opened 2023-09-16 03:40 UTC by e-dong

2023-09-16 16:58 UTC, e-dong commented
@Proryanator Using metadata.created() works for me lol
https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.created

I also added regex to match the ffmpeg log files instead filtering through all files within the current directory.

I pushed up what I have for now, I will do a cleanup when I get home later.

2023-09-17 02:47 UTC, e-dong commented
TODO

- [ ] Update unit tests
- [ ] cleanup code
- [ ] full run of permutator-cli

2023-09-18 17:11 UTC, Proryanator commented
@e-dong I think more work to get unit tests to run for linux is needed (like a linux job for example), so you can exclude unit testing from your checklist I think!

I opened another issue though for adding build pipelines for Linux.

2023-09-18 20:40 UTC, Proryanator commented on ffmpeg/src/report_files.rs
> +    let re = Regex::new(r"^ffmpeg.*?\.log$").unwrap();
Nice touch here! Pulling even more specific files 👏

2023-09-18 20:44 UTC, Proryanator commented on ffmpeg/src/report_files.rs
> +        fs::create_dir("./log-test").unwrap();
I like the addition of extra file types here 👍 can you add the file `diff-file-ext.txt` to the .gitignore? If the unit test fails that file won't get cleaned up, and will showup for git to commit.

Should just be an entry at the end of the `.gitignore` of:

`/ffmpeg/log-test/diff-file-ext.txt`

2023-09-18 20:54 UTC, Proryanator commented on ffmpeg/src/report_files.rs
> +        fs::remove_dir_all("./log-test").unwrap();
Can you also make this call to delete these files at the beginning of the test too?

If you ran this test, it failed, and didn't delete the files, it would throw an error that it can't create the setup files for testing.

(first call to delete this can ignore if the directory is not there too).

2023-09-18 20:59 UTC, Proryanator commented on ffmpeg/src/report_files.rs
> +            .contains("ffmpeg-2.log"));
The unit test fails here 🤔 although it passes on my local machine. I think you can safely use the `FileTime::from_last_modification_time(&metadata).unwrap();` call that was working with Windows before in `get_latest_log`.

(This does work on my machine too so, should get the test working again).

2023-09-18 21:02 UTC, Proryanator requested changes
@e-dong nice work! Left a few comments for you to work on.

Odd that one of the unit tests failed in the github workflow.

2023-09-19 01:41 UTC, e-dong commented on ffmpeg/src/report_files.rs
> +    let re = Regex::new(r"^ffmpeg.*?\.log$").unwrap();
thanks! just in case there are many unrelated files

2023-09-19 01:45 UTC, e-dong commented on ffmpeg/src/report_files.rs
> +            .contains("ffmpeg-2.log"));
hmm, when i didn't use `file.sync_all()` the creation timestamp of both files were the same. i can debug with printing the metadata and see what values the workflow prints out

2023-09-19 02:21 UTC, e-dong commented on ffmpeg/src/report_files.rs
> +            .contains("ffmpeg-2.log"));
Added some tmp changes that I will revert after testing:
41e8b5fa74765a18ea5fa50db669d5daf6ff991b

2023-09-22 20:48 UTC, Proryanator commented
> @Proryanator What do you think of using the [tempfile crate](https://docs.rs/tempfile/latest/tempfile/index.html) for handling temp dirs/files?

Could be a good feature request! I'd say don't worry about adding that into this PR though to keep the scope straight forward.

2023-09-22 21:44 UTC, e-dong commented
> > @Proryanator What do you think of using the [tempfile crate](https://docs.rs/tempfile/latest/tempfile/index.html) for handling temp dirs/files?
> 
> Could be a good feature request! I'd say don't worry about adding that into this PR though to keep the scope straight forward.

 Sounds good!

2023-09-23 00:48 UTC, e-dong commented on ffmpeg/src/report_files.rs
> +        fs::create_dir("./log-test").unwrap();
I added a wildcard to be more flexible in the future:
`ffmpeg/*log*`

2023-09-23 00:51 UTC, e-dong commented on ffmpeg/src/report_files.rs
> +        fs::remove_dir_all("./log-test").unwrap();
Done!

2023-09-23 00:52 UTC, e-dong commented on ffmpeg/src/report_files.rs
> +            .contains("ffmpeg-2.log"));
@Proryanator Do you mind approving the workflow? I want to see what values are printed for the metadata:
```
        //debug
        for file in &log_files {
            println!("{:?}", file.file_name());
            println!("{:?}", &file.metadata().unwrap());
        }
```

2023-09-23 00:57 UTC, e-dong commented on .github/workflows/pull_request_workflow.yml
> +        run: cargo test --no-fail-fast -- --show-output
Will revert after debugging the file metadata

2023-09-24 17:30 UTC, Proryanator commented
I think there's a variable problem (if you see the unit test failure). If you can fix that I can re-run the pipeline!

2023-09-24 20:33 UTC, e-dong commented
> I think there's a variable problem (if you see the unit test failure). If you can fix that I can re-run the pipeline!

Whoops nice catch :+1:

2023-09-26 17:02 UTC, Proryanator approved these changes

2023-09-26 23:06 UTC, merged