Add retry logic to check encode quality
Proryanator/encoder-benchmark pull request #32
Opened 2023-09-27 01:20 UTC by e-dong

Addresses #31 

## Summary of Changes
* Added timeout and listen_timeout to listen url [FFmpeg Protocols Documentation#tcp](https://ffmpeg.org/ffmpeg-protocols.html#tcp)
* Added retry logic when vmaf child process times out
* Ran `rustfmt` to format edited files  
   
![2023-09-26-215459_1920x436_scrot](https://github.com/Proryanator/encoder-benchmark/assets/16567905/e93cebcc-22b3-462a-a3a0-a643dabbdc24)

2023-09-27 01:24 UTC, e-dong commented
@Proryanator Standby, gonna rebase this branch. The commit history is pretty messy lol

2023-09-27 16:07 UTC, Proryanator requested changes
This is great! :D no more getting stuck when trying to calculate the vmaf score.

A few comments but otherwise looks great!

Also also, I'm going to add an issue to update the README with how to run rustfmt, and how to run that within your IDE as well (huge fan of standardized formatting when collaborating).

2023-09-27 16:39 UTC, e-dong commented on engine/src/permutation_engine.rs
> +                    print!("  [ATTEMPT {}/{}] ", attempt + 1, MAX_ATTEMPTS_CALC_QUALITY);
Yeah absolutely, the end user probably wouldn't care haha.

2023-09-27 16:40 UTC, e-dong commented on engine/src/permutation_engine.rs
> -                result.vmaf_score = check_encode_quality(permutation.clone(), &ctrl_channel, permutation.verbose);
Yeah that makes sense!

2023-09-29 00:32 UTC, e-dong commented on engine/src/permutation_engine.rs
> +                    print!("  [ATTEMPT {}/{}] ", attempt + 1, MAX_ATTEMPTS_CALC_QUALITY);
![2023-09-28-203146_1388x128_scrot](https://github.com/Proryanator/encoder-benchmark/assets/16567905/f62fe395-49bb-4a4d-b06e-41890f6a20c9)

Yeah that's a lot cleaner!

2023-09-29 10:47 UTC, e-dong commented on engine/src/permutation_engine.rs
> +                    print!("  [ATTEMPT {}/{}] ", attempt + 1, MAX_ATTEMPTS_CALC_QUALITY);
Added some more verbose logs
```
[00:00:10] [----------------] 0/2383 frames (00:00:00)                                                      VMAF calculation finishing up...                       tcp://localhost:2000?listen&listen_timeout=3000&timeout=1000000: Connection timed out
See perm-278-attempt-1-ffmpeg-20230929-033554.log for more details.                                           Check encode quality failed. Retrying...               [ ATTEMPT 2/3 ] Calculating vmaf score; might take longer than original encode depending on your CPU...
...
```

2023-09-29 12:25 UTC, e-dong commented on engine/src/permutation_engine.rs
> +                    print!("  [ATTEMPT {}/{}] ", attempt + 1, MAX_ATTEMPTS_CALC_QUALITY);
I actually might swap the filename around, so the attempts are sorted by timestamp first.
Failed 3 times.

```
perm-175-attempt-1-ffmpeg-20230929-022024.log
      perm-253-attempt-1-ffmpeg-20230929-031736.log
      perm-278-attempt-1-ffmpeg-20230929-033554.log
```

2023-09-29 20:40 UTC, Proryanator approved these changes

2023-09-29 20:41 UTC, merged