Add aur pkgbuild
Proryanator/encoder-benchmark pull request #37
Opened 2023-09-30 17:07 UTC by e-dong

2023-10-03 22:56 UTC, e-dong commented
- [x] Complete Review on [PKGBUILD from reddit lol](https://www.reddit.com/r/archlinux/comments/16xn3l9/first_time_publishing_pkgbuild_to_aur/)

2023-10-11 04:06 UTC, e-dong commented
@Proryanator I think this is the last item to do.
 
- [ ] Add a README in `packaging/linux/aur` for setup and contribution instructions

2023-10-12 23:49 UTC, e-dong commented
@Proryanator Hey man, I finally found time to get this done haha. You can read my README from my [fork here](https://github.com/e-dong/encoder-benchmark/tree/add-aur-pkgbuild/packaging/linux/aur).

Let me know if I should add anything else or something isn't clear :smile:

2023-10-17 19:13 UTC, Proryanator commented on packaging/linux/aur/README.md
> +1. In your local cloned copy of `encoder-benchmark`, run `git submodule update --init`. The submodules should be initialized and cloned.
Really like that you put these instructions in here, was wondering how I could become a package co-maintainer! Small nit, could you fix the numbered list?

2023-10-17 19:14 UTC, Proryanator commented on packaging/linux/aur/README.md
> +
Might be good to add a small generic section here as to how the aur package is pulled (i.e. does aur periodically poll this repo to pull the latest changes, would only be on `main`, etc).

Totally optional but for those not familiar would be a nice how-to.

2023-10-17 19:15 UTC, Proryanator requested changes
Small nit on the extra readme and a question! Otherwise looks great.

2023-10-26 11:15 UTC, e-dong commented on packaging/linux/aur/README.md
> +1. In your local cloned copy of `encoder-benchmark`, run `git submodule update --init`. The submodules should be initialized and cloned.
Thanks! Let me know once you create an AUR account, I will have to add you as a comaintainer once you setup your username.

Ooh what was wrong with the numbered list? Using all `1.` renders them sequentially automatically.

2023-10-26 11:56 UTC, e-dong commented on packaging/linux/aur/README.md
> +
AUR actually doesn't poll this repo. It is actually uncommon to have this repo (upstream) link to the AUR. This is because usually different/unrelated people create the AUR for a git repo. So we are in a unique situation haha.

The target audience for this README is for devs maintaining the AUR. We would need a section on the main readme to target end users that want to use AUR.

The `encoder-benchmark` source is tied to the tag. So when you release a new tag, I would update the `pkgver`
See: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=encoder-benchmark#n13

The `encoder-benchmark-git` source pulls the latest from `main` at the time of building with `makepkg`. The user is responsible for keeping track of when there are updates upstream. When there is a new release, I would push a metadata update.
The arch wiki says:
>Do not commit mere pkgver bumps for [VCS packages](https://wiki.archlinux.org/title/VCS_package_guidelines). They are not considered out of date when the upstream has new commits. Only do a new commit when other changes are introduced, such as changing the build process.

ref: https://wiki.archlinux.org/title/AUR_submission_guidelines

2023-10-27 01:47 UTC, Proryanator commented on packaging/linux/aur/README.md
> +1. In your local cloned copy of `encoder-benchmark`, run `git submodule update --init`. The submodules should be initialized and cloned.
Ha! Nothing wrong at all, I didn't realize that was a thing 😅

2023-10-27 02:10 UTC, e-dong commented
@Proryanator Let's have links to the AUR in the root README

2023-10-27 12:15 UTC, Proryanator commented
> @Proryanator Let's have links to the AUR in the root README

Updated #45 to include linking to this readme.

2023-10-27 12:15 UTC, Proryanator approved these changes

2023-10-27 12:16 UTC, merged